export { default as AddLaptop } from "./AddLaptop/AddLaptop";
export { default as Auth } from "./Auth/Auth";
export { default as Cart } from "./Cart/Cart";
export { default as Home } from "./Home/Home";
export { default as Laptops } from "./Laptops/Laptops";
export { default as Profile } from "./Profile/Profile";
export { default as LaptopDetails } from "./LaptopDetails/LaptopDetails";
export { default as ProfileSettings } from "./ProfileSettings/ProfileSettings";
export { default as Roles } from "./Roles/Roles";
